name: Thomas Belin
url: "http://blog.thomasbelin.fr"
description: Full-Stack développeur chez doyoubuzz. Je fais la part belle au code. Je m'éclate avec Javascript.
title: JS rocks
permalink: /p/:title/
exclude: [node_modules, package.json, gulpfile.js, vendor]
sass:
    sass_dir: css/_sass
gems:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

author:
    twitter: atomrc
    name: atomrc
    uri: https://twitter.com/atomrc
twitter:
    username: atomrc
collections:
    talks:
        output: true

defaults:
    -
        scope:
            type: posts
        values:
            layout: post
            image: http://www.gravatar.com/avatar/56f2389bd912f388cc79874ce65fc0dc?s=200
    -
        scope:
            type: talks
        values:
            permalink: /talks/:title/
